sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - lombok
      - udf_coverage
      - jar_artifact
excludes:
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build.yml'"