sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - lombok
      - udf_coverage
      - jar_artifact
linkReplacements:
  - "LICENSE-exasol-jdbc.txt|https://docs.exasol.com/db/latest/connect_exasol/drivers/jdbc.htm#License"
excludes:
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build.yml'"
  - "E-PK-CORE-18: Outdated content: 'src/assembly/all-dependencies.xml'"
