language: java

# Setting sudo to false will cause Travis to use Containers.
# To use Docker's privileged mode, we need to enable sudo.
sudo: required

jdk:
  - openjdk11

env:
  - DOCKER_DB_VERSION=7.0.2
  - DOCKER_DB_VERSION=6.2.12

addons:
  sonarcloud:
    organization: exasol

# Create an empty Docker config to avoid error message about missing config.
before_script:
  - mkdir "$HOME"/.docker
  - echo '{}' > "$HOME"/.docker/config.json
  - echo 'docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy' > "$HOME"/.testcontainers.properties
  - echo 'testcontainers.reuse.enable=true' >> "$HOME"/.testcontainers.properties

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:prepare-agent-integration
    verify sonar:sonar
    -Dsonar.login=${SONAR_TOKEN}
    -Dcom.exasol.docker.image=${DOCKER_DB_VERSION}
    -Dtest.coverage="true"
    -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml

cache:
  directories:
    - "$HOME/.m2"