language: java
matrix:
  include:
    - jdk: openjdk11
addons:
  sonarcloud:
    organization: exasol

before_script:
  - ./tools/version.sh verify

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=com.exasol:row-level-security -Dsonar.login=${SONAR_TOKEN}
cache:
  directories:
    - "$HOME/.m2"