language: java

# Setting sudo to false will cause Travis to use Containers.
# To use Docker's privileged mode, we need to enable sudo.
sudo: required

matrix:
  include:
    - jdk: openjdk11

addons:
  sonarcloud:
    organization: exasol

before_script:
  - ./tools/version.sh verify

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:prepare-agent-integration verify sonar:sonar -Dsonar.projectKey=com.exasol:row-level-security -Dsonar.login=${SONAR_TOKEN}
cache:
  directories:
    - "$HOME/.m2"