name: CI Build

on:
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        docker_db_version: [ 7.0.16, 7.1.6 ]
    env:
      DEFAULT_DB_VERSION: "7.1.6"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Configure Testcontainers
        run: |
          echo '{}' > "$HOME"/.docker/config.json
          echo 'docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy' > "$HOME"/.testcontainers.properties
          echo 'testcontainers.reuse.enable=true' >> "$HOME"/.testcontainers.properties
      - name: Run tests and build with Maven
        run: mvn --batch-mode --update-snapshots clean verify -DtrimStackTrace=false -Dcom.exasol.dockerdb.image=${{ matrix.docker_db_version }}
      - name: Publish Test Report for ${{ matrix.docker_db_version }}
        uses: scacap/action-surefire-report@v1
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sonar analysis
        if: ${{ env.DEFAULT_DB_VERSION == matrix.docker_db_version }}
        run: mvn --batch-mode sonar:sonar -Dsonar.organization=exasol -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}